export const KIOSK_STATES = Object.freeze({
  BOOTING: "BOOTING",
  CONFIG_LOADING: "CONFIG_LOADING",
  CONFIG_ERROR: "CONFIG_ERROR",
  LOCKED_UNASSIGNED: "LOCKED_UNASSIGNED",
  IDLE: "IDLE",
  OFFLINE_IDLE: "OFFLINE_IDLE",
  TAP_READING: "TAP_READING",
  INTERACTION_ACTIVE: "INTERACTION_ACTIVE",
  INTERACTION_EXCEPTION: "INTERACTION_EXCEPTION",
  SYNCING_BACKGROUND: "SYNCING_BACKGROUND",
  READER_ERROR: "READER_ERROR",
  DIAGNOSTICS: "DIAGNOSTICS"
});

const ALLOWED_TRANSITIONS = {
  [KIOSK_STATES.BOOTING]: [KIOSK_STATES.CONFIG_LOADING],
  [KIOSK_STATES.CONFIG_LOADING]: [
    KIOSK_STATES.IDLE,
    KIOSK_STATES.OFFLINE_IDLE,
    KIOSK_STATES.CONFIG_ERROR,
    KIOSK_STATES.LOCKED_UNASSIGNED
  ],
  [KIOSK_STATES.IDLE]: [
    KIOSK_STATES.TAP_READING,
    KIOSK_STATES.READER_ERROR,
    KIOSK_STATES.DIAGNOSTICS,
    KIOSK_STATES.SYNCING_BACKGROUND,
    KIOSK_STATES.OFFLINE_IDLE
  ],
  [KIOSK_STATES.OFFLINE_IDLE]: [
    KIOSK_STATES.TAP_READING,
    KIOSK_STATES.DIAGNOSTICS,
    KIOSK_STATES.READER_ERROR,
    KIOSK_STATES.SYNCING_BACKGROUND
  ],
  [KIOSK_STATES.TAP_READING]: [
    KIOSK_STATES.INTERACTION_ACTIVE,
    KIOSK_STATES.INTERACTION_EXCEPTION
  ],
  [KIOSK_STATES.INTERACTION_ACTIVE]: [KIOSK_STATES.IDLE, KIOSK_STATES.OFFLINE_IDLE],
  [KIOSK_STATES.INTERACTION_EXCEPTION]: [KIOSK_STATES.IDLE, KIOSK_STATES.OFFLINE_IDLE],
  [KIOSK_STATES.READER_ERROR]: [KIOSK_STATES.IDLE, KIOSK_STATES.OFFLINE_IDLE],
  [KIOSK_STATES.SYNCING_BACKGROUND]: [KIOSK_STATES.IDLE, KIOSK_STATES.OFFLINE_IDLE],
  [KIOSK_STATES.DIAGNOSTICS]: [KIOSK_STATES.IDLE, KIOSK_STATES.OFFLINE_IDLE],
  [KIOSK_STATES.CONFIG_ERROR]: [KIOSK_STATES.CONFIG_LOADING],
  [KIOSK_STATES.LOCKED_UNASSIGNED]: [KIOSK_STATES.CONFIG_LOADING]
};

export function assertTransition(fromState, toState) {
  const allowed = ALLOWED_TRANSITIONS[fromState] ?? [];
  if (!allowed.includes(toState)) {
    throw new Error(`Invalid kiosk transition: ${fromState} -> ${toState}`);
  }
  return toState;
}
