// Central catalogue of application-level error codes.
// All codes are thrown as HttpError(statusCode, code) — consumers check error.message for the code.

export const ERROR_CODES = Object.freeze({
  // Scope enforcement (HTTP 403)
  EVENT_SCOPE_FORBIDDEN: "EVENT_SCOPE_FORBIDDEN",
  STALL_SCOPE_FORBIDDEN: "STALL_SCOPE_FORBIDDEN",
  PACKAGE_SCOPE_FORBIDDEN: "PACKAGE_SCOPE_FORBIDDEN",

  // Status transition guards (HTTP 400)
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  EVENT_LOCKED: "EVENT_LOCKED",

  // Checklist / go-live guards (HTTP 422)
  CHECKLIST_INCOMPLETE: "CHECKLIST_INCOMPLETE",
  GO_LIVE_BLOCKED: "GO_LIVE_BLOCKED",

  // Confirmation guards (HTTP 400)
  CONFIRMATION_NAME_MISMATCH: "CONFIRMATION_NAME_MISMATCH",

  // Auth errors
  INVITE_TOKEN_INVALID_OR_EXPIRED: "INVITE_TOKEN_INVALID_OR_EXPIRED",
  RESET_TOKEN_INVALID_OR_EXPIRED: "RESET_TOKEN_INVALID_OR_EXPIRED",
  CURRENT_PASSWORD_INCORRECT: "CURRENT_PASSWORD_INCORRECT",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK"
});
